name: AoWPlugin
main: paragasu.arenaofwolves.aowplugin.AoWPlugin
version: 1.0
commands:
  summonwolf:
    description: This is a command summoning a wolf.
    aliases: sw
    usage: /<command> [str] [con] [int] [dex] [WolfType]
    permission: aowplugin.sw
    permission-message: You don't have <permission>
  worldname:
    description: test
    usage: /<command>
    permission: aowplugin.test
    permission-message: sine
  test:
    usage: /<command>
    permission: aowplugin.test
    permission-message: sine
permissions:
  aowplugin.sw:
    default: true
  aowplugin.test:
    default: op